#!/bin/bash

function cardano-node-docker-init() {

  test -z "${CARDANO_NODE_COMMIT+x}" && CARDANO_NODE_COMMIT=master
  test -z "${DOCKER_REPOSITORY+x}" && DOCKER_REPOSITORY=registry.local:5000
  test -z "${DOCKER_IMAGE_NAME+x}" && DOCKER_IMAGE_NAME=rcmorano/cardano-node
  test -z "${DOCKER_IMAGE_SUFFIX+x}" && DOCKER_IMAGE_NAME=""
  test -z "${DOCKER_IMAGE_URI+x}" && DOCKER_IMAGE_URI=${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}
  test -z "${DOCKER_SRC_TARGETS+x}" && DOCKER_SRC_TARGETS="bin-build"
  test -z "${DOCKER_FINAL_TARGETS+x}" && DOCKER_FINAL_TARGETS="guild-ops-ptn0-passive iohk-stn-passive"

}

function cardano-node-docker-pull-cache() {

  SRC_IMAGE=${DOCKER_IMAGE_URI}:src-${CARDANO_NODE_COMMIT}
  BUILD_IMAGE=${DOCKER_IMAGE_URI}:src-build-${CARDANO_NODE_COMMIT}

  docker pull ${SRC_IMAGE} || true
  docker pull ${BUILD_IMAGE} || true

}

function cardano-node-docker-build() {

  for target in ${DOCKER_SRC_TARGETS}
  do
    BUILD_IMAGE=${DOCKER_IMAGE_NAME}:${target}-${CARDANO_NODE_COMMIT}
    IMAGE_PRESENT=$(docker pull ${BUILD_IMAGE} &> /dev/null || echo false)
    if [[ "${IMAGE_PRESENT}" == "false" ]] || [[ -z "${IMAGE_PRESENT}" ]]
    then
      docker build \
        -f Dockerfile.${target} \
        --build-arg CARDANO_NODE_COMMIT=${CARDANO_NODE_COMMIT} \
        --cache-from ${BUILD_IMAGE} \
        --label docker-source-commit=${CI_COMMIT_SHORT_SHA} \
        --label cardano-node-commit=${CARDANO_NODE_COMMIT} \
        -t ${BUILD_IMAGE} \
        .
      if [ "${DOCKER_PUSH_IMAGES}" == "true" ]
      then
        docker push ${BUILD_IMAGE}
      fi
    fi
  done

  for target in ${DOCKER_FINAL_TARGETS}
  do
    BUILD_IMAGE=${DOCKER_IMAGE_NAME}:${target}${DOCKER_IMAGE_SUFFIX}
    docker pull ${BUILD_IMAGE} || true
    docker build \
      --cache-from ${BUILD_IMAGE} \
      --build-arg CARDANO_NODE_COMMIT=${CARDANO_NODE_COMMIT} \
      --target ${target} \
      -t ${BUILD_IMAGE} .
      if [ "${DOCKER_PUSH_IMAGES}" == "true" ]
      then
        DETAILED_TAG=$(docker inspect -f '{{ .Created }}' ${BUILD_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g')-${CI_COMMIT_SHORT_SHA}-${CARDANO_NODE_COMMIT}
        DETAILED_IMAGE=${BUILD_IMAGE}-${DETAILED_TAG}
        docker tag ${BUILD_IMAGE} ${DETAILED_IMAGE}
        docker push ${BUILD_IMAGE}
        docker push ${DETAILED_IMAGE}
      fi
  done

}
