FROM alpine AS src
RUN apk add --no-cache curl
ARG CARDANO_NODE_LINUX_TGZ=https://hydra.iohk.io/build/3175064/download/1/cardano-node-1.14.0-linux.tar.gz

RUN mkdir /output && \
    curl -sLo /tmp/cardano-node.tgz ${CARDANO_NODE_LINUX_TGZ} && \
    tar -zxf /tmp/cardano-node.tgz -C /output
