FROM alpine AS src
RUN apk add --no-cache curl
# FROM https://hydra.iohk.io/job/Cardano/cardano-node/cardano-node-linux/latest-finished
ARG CARDANO_NODE_LINUX_TGZ=https://hydra.iohk.io/build/3229750/download/1/cardano-node-1.14.0-linux.tar.gz

RUN mkdir /output && \
    curl -sLo /tmp/cardano-node.tgz ${CARDANO_NODE_LINUX_TGZ} && \
    tar -zxf /tmp/cardano-node.tgz -C /output

# wget -O $CNODE_HOME/files/topology.json https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/shelley_testnet-topology.json
#wget -O $CNODE_HOME/files/genesis.json https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/shelley_testnet-genesis.json
